name: Render 3D PCB Images
on: [push]

jobs:
  render-board:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Generate 3D PCB Renders
        uses: linalinn/kicad-render@main
        with:
          pcb_file: "My First PCB.kicad_pcb"
          output_path: ${{ github.workspace }}/images
          animation: gif
          
      - name: Deploy Renders to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/images
